### ISSUE TITLE
no work!!!

### ISSUE THREAD

**Issue by pauliusbaulius** [hcbt/pybooks#1]
hello
i install this application
i type python3
opens promt??????????
>>>

where do i start!! program!! 
very bad pls fix
@hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt @hcbt

**Comment by hcbt** [comment]
Please read README.md 
Marked as solved
